/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package css121p.finalproject.UI;

import css121p.finalproject.database.InventorySystem;
import css121p.finalproject.data.Lot;
import css121p.finalproject.data.Buyer;
import css121p.finalproject.data.Block;
import static css121p.finalproject.data.Status.AVAILABLE;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.border.EmptyBorder;
import java.awt.Component;




/**
 *
 * @author Jan Denisse
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jTable1.setModel(InventorySystem.getInstance().tableReport);
        setUpHouseGrid();
        InventorySystem.getInstance().tableReport.setRowCount(0);
        InventorySystem.getInstance().reportLot();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MapContainer = new javax.swing.JPanel();
        MapGrid = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        HouseGrid = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buyerTab = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNum = new javax.swing.JTextField();
        txtL = new javax.swing.JTextField();
        buyBtn = new javax.swing.JButton();
        rsrvBtn = new javax.swing.JButton();
        txtB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Real Estates Management App");
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MapContainer.setBackground(new java.awt.Color(102, 102, 102));
        MapContainer.setMaximumSize(new java.awt.Dimension(600, 500));
        MapContainer.setPreferredSize(new java.awt.Dimension(600, 500));
        MapContainer.setLayout(new java.awt.GridBagLayout());

        MapGrid.setBackground(new java.awt.Color(51, 51, 51));
        MapGrid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MapGrid.setMaximumSize(new java.awt.Dimension(600, 500));
        MapGrid.setPreferredSize(new java.awt.Dimension(600, 500));
        MapGrid.setLayout(new java.awt.CardLayout());

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), "Subdivision 1 Village Map", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(544, 534));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        HouseGrid.setBackground(new java.awt.Color(255, 255, 255));
        HouseGrid.setMaximumSize(new java.awt.Dimension(600, 600));
        HouseGrid.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HouseGridLayout = new javax.swing.GroupLayout(HouseGrid);
        HouseGrid.setLayout(HouseGridLayout);
        HouseGridLayout.setHorizontalGroup(
            HouseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HouseGridLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HouseGridLayout.setVerticalGroup(
            HouseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HouseGridLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.add(HouseGrid, "card2");

        MapGrid.add(jLayeredPane1, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        MapContainer.add(MapGrid, gridBagConstraints);

        jTabbedPane1.addTab("View Lots", MapContainer);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Lots Report", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new java.awt.BorderLayout());

        buyerTab.setBackground(new java.awt.Color(153, 204, 0));
        buyerTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyerTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        buyerTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buyBtn.setText("Buy");
        buyBtn.addActionListener(this::buyBtnActionPerformed);

        rsrvBtn.setText("Reserve");
        rsrvBtn.addActionListener(this::rsrvBtnActionPerformed);

        txtB.addActionListener(this::txtBActionPerformed);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Register as a client:");

        jLabel3.setText("Input block:");

        jLabel2.setText("Input contact:");

        jLabel1.setText("Input name:");

        jLabel4.setText("Input lot:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtL)
                            .addComponent(txtB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rsrvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyBtn)
                    .addComponent(rsrvBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(365, 365, 365))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        buyerTab.addTab("Buyer Registration", jPanel5);

        jPanel4.add(buyerTab, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Buyer", jPanel4);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void rsrvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsrvBtnActionPerformed
        try {
            InventorySystem database = InventorySystem.getInstance();
            String name = txtName.getText();
            String contact = txtNum.getText();
            int block = Integer.parseInt(txtB.getText());
            int lot = Integer.parseInt(txtL.getText());

            Buyer b = new Buyer(name, contact);

            database.reportLot(block, lot);
            showLotDetailsPopup(block, lot);

            if (database.getLotStatus(block, lot) == AVAILABLE) {
                database.processReservation(b, block, lot);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Block " + block + " Lot " + lot + " is already taken!",
                    "Reservation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            database.reportLot();
            setUpHouseGrid();

            int index = buyerTab.indexOfTab(name);
            JPanel targetTab;

            if (index == -1) {
                targetTab = new JPanel(new java.awt.FlowLayout());
                targetTab.add(new JLabel("Welcome " + name));
                targetTab.add(new JLabel("Actions for " + name));
                buyerTab.addTab(name, targetTab);
            } else {
                targetTab = (JPanel) buyerTab.getComponentAt(index);
                buyerTab.setSelectedIndex(index);
            }

            JButton buyBtn = new JButton("Buy House Block: " + block + " Lot: " + lot);
            targetTab.add(buyBtn);

            buyBtn.addActionListener(e -> {
                database.processPurchase(b, block, lot);

                database.reportLot();
                setUpHouseGrid();
                this.revalidate();
                this.repaint();

                targetTab.remove(buyBtn);

                JButton newSellBtn = new JButton("Sell House Block: " + block + " Lot: " + lot);
                targetTab.add(newSellBtn);

                newSellBtn.addActionListener(sellEvent -> {
                    database.processSell(b, block, lot);
                    targetTab.remove(newSellBtn);

                    database.reportLot();
                    setUpHouseGrid();
                    this.revalidate();
                    this.repaint();

                    if (targetTab.getComponentCount() <= 2) {
                        buyerTab.remove(targetTab);
                    } else {
                        targetTab.revalidate();
                        targetTab.repaint();
                    }
                    javax.swing.JOptionPane.showMessageDialog(this, "Lot sold!");
                });

                targetTab.revalidate();
                targetTab.repaint();

                javax.swing.JOptionPane.showMessageDialog(this, "Lot bought! Tab updated to Seller mode.");
            });

            targetTab.revalidate();
            targetTab.repaint();
            setUpHouseGrid();

            javax.swing.JOptionPane.showMessageDialog(this, "Reserve Successful");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number format (Blocks: [1-5] Lots:[1-20])");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_rsrvBtnActionPerformed

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        try {

            InventorySystem database = InventorySystem.getInstance();

            String name = txtName.getText();
            String contact = txtNum.getText();
            int block = Integer.parseInt(txtB.getText());
            int lot = Integer.parseInt(txtL.getText());

            Buyer b = new Buyer(name, contact);

            database.reportLot(block, lot);

            showLotDetailsPopup(block, lot);

            if (database.getLotStatus(block, lot) == AVAILABLE) {
                database.processPurchase(b, block, lot);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Block " + block + " Lot " + lot + " is already taken!",
                    "Transaction Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            database.tableReport.setRowCount(0);
            database.reportLot();
            setUpHouseGrid();

            // --- TAB LOGIC START ---
            int index = buyerTab.indexOfTab(name);
            JPanel targetTab;

            if (index == -1) {
                targetTab = new JPanel(new java.awt.FlowLayout());
                targetTab.add(new JLabel("Welcome " + name));
                targetTab.add(new JLabel("Actions for " + name));
                buyerTab.addTab(name, targetTab);
            } else {
                targetTab = (JPanel) buyerTab.getComponentAt(index);
                buyerTab.setSelectedIndex(index);
            }

            JButton sellBtn = new JButton("Sell House Block: " + block + " Lot: " + lot);
            targetTab.add(sellBtn);

            sellBtn.addActionListener(e -> {
                database.processSell(b, block, lot);
                targetTab.remove(sellBtn); // Remove the specific button

                if (targetTab.getComponentCount() <= 2) {
                    buyerTab.remove(targetTab);
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Lot sold!");
                targetTab.revalidate();
                targetTab.repaint();
            });

            targetTab.revalidate();
            targetTab.repaint();
            setUpHouseGrid();

            javax.swing.JOptionPane.showMessageDialog(this, "Purchase Successful");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number format (Blocks: [1-5] Lots:[1-20])");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_buyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    public void setUpHouseGrid() {
    HouseGrid.removeAll(); 
    // Use Vertical BoxLayout so blocks stack top-to-bottom
    HouseGrid.setLayout(new javax.swing.BoxLayout(HouseGrid, javax.swing.BoxLayout.Y_AXIS));
    
    // Add significant padding to create the "Dashboard" feel
    HouseGrid.setBorder(new javax.swing.border.CompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new Color(200, 200, 200), 1), // Card outline
        javax.swing.BorderFactory.createEmptyBorder(20, 40, 20, 40) // Internal padding
    ));

    InventorySystem system = InventorySystem.getInstance();
    Block[] allBlocks = system.getBlocks();

    for (int i = 0; i < allBlocks.length; i++) {
        // 1. Block Label
        JLabel blockLabel = new JLabel(" BLOCK " + (i + 1) + " ");
        JLabel SPACE = new JLabel(" ");

        blockLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        blockLabel.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 14));
        HouseGrid.add(blockLabel);
        HouseGrid.add(SPACE);

        // 2. The Actual Grid - REMOVED the "Wrapper" that was killing the size
        // This GridLayout will now stretch to the width of HouseGrid
        JPanel blockGrid = new JPanel(new java.awt.GridLayout(2, 10, 4, 4));
        blockGrid.setOpaque(false);

        for (Lot l : allBlocks[i].getLots()) {
            // Create the square lot
            HouseGrid lotComponent = new HouseGrid(l);
            lotComponent.setPreferredSize(null); 
            blockGrid.add(lotComponent);
        }
        
        HouseGrid.add(blockGrid);
        HouseGrid.add(javax.swing.Box.createVerticalStrut(15)); // Space between blocks
    }

    // Force the UI to realize the "Russian Doll" panels are gone
    HouseGrid.revalidate();
    HouseGrid.repaint();
}
    public void showLotDetailsPopup(int block, int lotNum) {
    // 1. Redirect System.out to a temporary stream
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    java.io.PrintStream ps = new java.io.PrintStream(baos);
    java.io.PrintStream old = System.out;
    System.setOut(ps);

    // 2. Call your existing method from the instance
    css121p.finalproject.database.InventorySystem.getInstance().reportLot(block, lotNum);

    // 3. Restore the original System.out
    System.out.flush();
    System.setOut(old);

    // 4. Show the captured string in a popup
    String output = baos.toString();
    javax.swing.JOptionPane.showMessageDialog(this, output, "Lot Details", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HouseGrid;
    private javax.swing.JPanel MapContainer;
    private javax.swing.JPanel MapGrid;
    private javax.swing.JButton buyBtn;
    private javax.swing.JTabbedPane buyerTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton rsrvBtn;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}



